---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "God-King Skovald"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if (unit:AuraRemaining("Water Bubble", "HELPFUL") > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    end

    return false
end

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    return true
end