---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Rasha'nan"
printTo(3,bossString)
WGBM[bossString] = {}

--[[WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('Nerub-ar Palace')
    if unit.name == "Rasha'nan" then
        if unit.health_percent < 0.59 then return end
        if (C_UnitAuras.GetBuffDataByIndex(unit.unitid, 2)) then return end
        return true
    end

    return
end]]

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].EnoughTimeToCast = function(spell, unit, args)
    local silenceCastRemains = CastTimeRemaining("boss1", "Deafening Screech")
    local mySpellCastTime = WarGod.Rotation.CastTimeFor(spell)
    if mySpellCastTime == 0 or silenceCastRemains == 0 then return true end
    if silenceCastRemains > 0 then
        if silenceCastRemains > (args.buffer or 0.5) + mySpellCastTime then
            return true
        else
            print('not casting ' .. spell .. ' due to incoming interrupt')
        end
    end
end

WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 10
    local name = unit.name
    if spell == "Fury of Elune" and name == "Rasha'nan" and GetMinimapZoneText() == "Mereldar" then
        print("need to add something to filter for p2 only")
        return 0, bossString
    end

    if UnitIsUnit("target", unitid) then
        score = score + 5
    end
    return score
end