---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Tidesage Council"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    if (unit:AuraRemaining("Reinforcing Ward", "HELPFUL") > 0) then
        --printTo(3,'not dpsing with Soul Armor buff')
        --return true
    end

    return false
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    -- only interrupt if you have the debuff thingy on you (thinking priority is to not get multiple stacks, rather than to avoid them entirely
    if (WarGod.Unit:GetPlayer():AuraRemaining("Slicing Blast", "HARMFUL") > 0) then
        return true

    end
end

WGBM[bossString].Preheal = function(spell, unit, args)
    local unitid = unit.unitid
    if UnitIsUnit("boss1target", unitid) or UnitIsUnit("boss2target", unitid) then
        print("keeping bubbles on everyone with aggro")
        return true
    end
    return true
end

print("Tidesage Council")