---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Lord Stormsong"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid


    return false
end

WGBM[bossString].Purge = function(spell, unit, args)
    return
end


WGBM[bossString].Interrupt = function(spell, unit, args)
    if UnitClass("player") == "Druid" then
        local specIndex = GetSpecialization()
        if specIndex == 2 or specIndex == 3 then
            return
        end
    end
    return true
    --printTo(3,'default interrupt')
end