    ---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods
local groups = WarGod.Unit.groups

local bossString = "Vol'zith the Whisperer"
printTo(3,bossString)
WGBM[bossString] = {}

--[[WGBM[bossString].DPSBlacklist = function(spell, unit, args)
--    local unitid = unit.unitid
    local name = unit.name
    if (name == "Sunken Denizen" and UnitGroupRolesAssigned("player") == "DAMAGER" and not UnitIsUnit("target", unitid)) then
        --printTo(3,'not dpsing with Soul Armor buff')
        return true
    end
    if (name == "Forgotten Denizen" and UnitGroupRolesAssigned("player") ~= "DAMAGER" and not UnitIsUnit("target", unitid)) then
        return true

    end
    return false
end]]

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if name == bossString and UnitChannelInfo("boss1") == "Grasp of the Sunken City" then
        return true
    elseif name == "Sunken Denizen" or name == "Forgotten Denizen" then
        if UnitIsUnit(unitid, "target") then
            return

        else
            return true
        end
    elseif UnitIsPlayer(unitid) == true then
        return true
    else
        return
    end

    --[[local dpsMobExists = false
    local tankMobExists = false
    for k,thisUnitId in pairs(groups.harmOrPlates) do
        if UnitName(thisUnitId) == "Forgotten Denizen" then
            dpsMobExists = true
        end
        if UnitName(thisUnitId) == "Sunken Denizen" then
            tankMobExists = true
        end
    end
    local myRole = UnitGroupRolesAssigned("player")
    local UnitRole = UnitGroupRolesAssigned("party1")
    if (myRole == "DAMAGER") then
        if (UnitRole == "DAMAGER") then
            return false
        elseif (UnitIsUnit("target", unitid)) then
            print('dpsing ' .. (unit.name or "") .. " cause targeting")
            return false
        elseif (tankMobExists) then
            print("not dpsing " .. (unit.name or "") .. " cause tank mob exists")
            return true
        else
            return false
        end
    end
    if (myRole ~= "DAMAGER") then
        if (UnitRole ~= "DAMAGER") then
            return false
        elseif (UnitIsUnit("target", unitid)) then
            print('dpsing ' .. (unit.name or "") .. " cause targeting")
            return false
        elseif (dpsMobExists) then
            print("not dpsing " .. (unit.name or "") .. " cause dps mob exists")
            return true
        else
            return false
        end
    end]]
end

WGBM[bossString].FriendlyBlacklist = function(spell, unit, args)
    --local name = UnitName("target")
    local unitid = unit.unitid
    if UnitIsUnit(unitid, "player") then
        return
    elseif unit:DebuffRemaining("Subverted Thoughts","HARMFUL") > 0 then
        return true
    else
        if UnitChannelInfo("boss1") == "Grasp of the Sunken City" then
            if UnitGroupRolesAssigned("player") == "DAMAGER" then
                if UnitGroupRolesAssigned(unitid) == "DAMAGER" then
                    return
                end
            end
            if UnitGroupRolesAssigned("player") ~= "DAMAGER" then
                if UnitGroupRolesAssigned(unitid) ~= "DAMAGER" then
                    return      -- healers or tanks
                end
            end
            if UnitPhaseReason(unitid) ~= nil then
                return
            end
            return true
        end
    end
    --[[local dpsMobExists = false
    local tankMobExists = false
    for k,thisUnitId in pairs(groups.harmOrPlates) do
        if UnitName(thisUnitId) == "Forgotten Denizen" then
            dpsMobExists = true
        end
        if UnitName(thisUnitId) == "Sunken Denizen" then
            tankMobExists = true
        end
    end
    local myRole = UnitGroupRolesAssigned("player")
    local UnitRole = UnitGroupRolesAssigned("party1")
    if (myRole == "DAMAGER") then
        if (UnitRole == "DAMAGER") then
            return false
        elseif (tankMobExists) then
            print("not healing " .. (unit.name or "") .. " cause tank mob exists")
            return true
        else
            return false
        end
    end
    if (myRole ~= "DAMAGER") then
        if (UnitRole ~= "DAMAGER") then

            return false
        elseif (dpsMobExists) then
            print("not healing " .. (unit.name or "") .. " cause dps mob exists")
            return true
        else
            return false
        end
    end
    return false]]
end

WGBM[bossString].Preheal = function(self, spell)
    --print("keeping bubbles on everyone")
    return true
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    return true
    --printTo(3,'default interrupt')
end
