---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Coin-Operated Crowd Pummeler"
printTo(3,bossString)
WGBM[bossString] = {}

--[[WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    if unit:DebuffRemaining("Fracking Totem", "HARMFUL") > 0 then
        return true
    end

    return false
]]

--[[WarGod.BossMods[bossString].Preheal = function(spell, unit, args)
    local unitid = unit.unitid
    print("keeping bubbles on everyone")
    return true
end]]

--[[WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 10
    local name = unit.name
    if unit:BuffRemaining("Azerite Infusion", "HELPFUL") > 0 then
        score = 20
    end
    if UnitIsUnit(unitid, "target") then
        score = score + 5
    end
    return score, bossString
end]]