---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "The MOTHERLODE!!"
printTo(3,bossString)
WGBM[bossString] = {}

--[[WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    if unit:BuffRemaining("Infested", "HELPFUL") > 0 then
        if not UnitIsUnit("target", unitid) then
            return true
        end
    end

    return false
end]]

WGBM[bossString].Purge = function(spell, unit, args)
    local unitid = unit.unitid
    local remains, stacks = unit:DebuffRemaining("Enrage", "HELPFUL")
    if remains > 0 and remains < 2 then
        return
    end
    if UnitClassification(unitid) == "elite" then
        return true
    end
    return true
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local casting = UnitCastingInfo(unitid)
    if not casting then
        casting = UnitChannelInfo(unitid)
    end
    if casting then
        if casting == "Rock Lance" then
            return
        elseif casting == "Shale Spit" then
            return
        elseif casting == "Caustic Compound" then
            return
        elseif casting == "Energy Lash" then
            return

        end
    end
    return true
    --printTo(3,'default interrupt')
end