---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Heartsbane Triad"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    --print('boo')
    if UnitCastingInfo(unitid) == "Claim the Iris" then
        return false
    elseif (unit:AuraRemaining("Soul Armor", "HELPFUL") > 0) then
        --printTo(3,'not dpsing with Soul Armor buff')
        return true
    elseif (unit:AuraRemaining("Runic Ward", "HELPFUL") > 0) then
        --printTo(3,'not dpsing with Runic Ward buff')
        return true

    elseif (unit:AuraRemaining("Ironbark Shield", "HELPFUL") > 0) then
        --printTo(3,'not dpsing with Ironbark Shield buff')
        return true

    elseif (unit:AuraRemaining("Soul Manipulation", "HELPFUL") > 0) then
        --printTo(3,'not dpsing while player MCd')
        return true

    elseif (unit:AuraRemaining("Aura of Thorns", "HELPFUL") > 0) then
        if (WarGod.Unit:GetPlayer().health_percent < 0.5 and UnitGroupRolesAssigned("player") == "DAMAGER") then
            --print("Not dpsing, low hp and thorns")
            return true
        end
    end

    return false
end

WGBM[bossString].Priority = function(spell, unit, args)
    --local spell, unit, args = ...
    --print(...)

    local unitid = unit.unitid
    local score = 10
    local unitname = unit.name
    --print(unitname)
    if unitid ~= "" then
        --print(unitid)
        if (not UnitIsUnit(unitid, "boss1")) and (not UnitIsUnit(unitid, "boss2")) and (not UnitIsUnit(unitid, "boss3")) then
            score = 20
        end

    end

    return score, bossString
end

WGBM[bossString].Cleanse = function(spell, unit, args)
    local unitid = unit.unitid
    if unit:BuffRemaining("Unstable Runic Mark", "HARMFUL") > 0 then
        return
    end
    return true
end

WGBM[bossString].Purge = function(spell, unit, args)
    --local unitid = unit.unitid
    return
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    return 1337
end