---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Waycrest Manor"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        --printTo(3,'not dpsing with Soul Armor buff')
        --return true
    --end
    if unit:BuffRemaining("Infested", "HELPFUL") > 0 then
        if not UnitIsUnit("target", unitid) then
            return true
        end

    end

    return false
end

WGBM[bossString].Cleanse = function(spell, unit, args)
    local unitid = unit.unitid
    if unit:BuffRemaining("Dread Mark", "HARMFUL") > 0 then
        return
    elseif unit:BuffRemaining("Runic Mark", "HARMFUL") > 0 then
        return true
    end
    return true
end

WGBM[bossString].Purge = function(spell, unit, args)
    local unitid = unit.unitid
    if UnitClassification(unitid) == "elite" then
        return true
    end
end