---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Neltharus"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local name = unit.name
    if (unit:AuraRemaining("Seal Empowerment", "HELPFUL") > 0) then
        print('not dpsing with Seal Empowerment buff')
        return true
    end
    if name == "Incorporeal Being" then return true end
    if WarGod.Rotations.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return false
end

WGBM[bossString].Priority = function(spell, unit, args)
    --if spell ~= "" then print('default priority') end
    local unitid = unit.unitid
    local name = unit.name
    local score = 10
    --print(unitid)
    --[[if (unit.name == "Explosives") then
        return 1000000, "default"
    elseif unit.health_percent < 0.95 and unit:BuffRemaining("Inspiring Presence", "HELPFUL") > 0 then
        return 5000, "default"
    end]]
    if name == "Binding Spear" then
        score = 50

    elseif name == "Qalashi Lavamancer" then
        local cast = UnitCastingInfo(unitid)
        local channel = UnitChannelInfo(unitid)
        if cast == "Molten Barrier" or channel == "Molten Army" and unit:BuffRemaining("Molten Barrier", "HELPFUL") ~= 0 then
            score = 40
        end
    end

    if UnitIsUnit("target", unitid) then
        score = score + 5
    end

    return score, bossString
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    if unit.name == "Stormsurge Totem" then return true end
end

WGBM[bossString].AoeBlacklisted = function(spell, unit, args)
    local name = unit.name
    if name == "Explosives" then
        return true
    elseif name == "Stormsurge Totem" then
        return true
    end
end

local ragingPurgeList = {
    --["Qalashi Warden"] = true,
    --["Apex Blazewing"] = true,
    --["Qalashi Lavamancer"] = true,
    ["Qalashi Hunter"] = true,
    --["Tamed Phoenix"] = true,
    --["Overseer Lahar"] = true,
    ["Qalashi Trainee"] = true,
    ["Qalashi Bonetender"] = true,
    --["Qalashi Spinecrusher"] = true,
    ["Ore Elemental"] = true,
    ["Qalashi Plunderer"] = true,
    ["Qalashi Thaumaturge"] = true,
    --["Qalashi Lavabearer"] = true,
    --["Lava Flare"] = true,
    ["Qalashi Bonesplitter"] = true,
    ["Qalashi Irontorch"] = true,
    --["Irontorch Commander"] = true,
    --["Qalashi Blacksmith"] = true,
    --["Forgewrought Monstrosity"] = true,

}

WGBM[bossString].Purge = function(spell, unit, args)
    --print('checking purge')
    local unitid = unit.unitid
    local name = unit.name
    local class = UnitClass("player")
    if class == "Druid" or class == "Rogue" or class == "Hunter" then
        --[[if unit:BuffRemaining("Painful Motivation", "HELPFUL") > 0 then
            print('do not dispel painful motivation')
            return
        end]]
        local dispelScore = 0
        for i=1,40 do
            local aura, icon, count, buffType, duration = UnitBuff(unitid, i)
            if not aura then break end--if (buffType) then print(buffType) end
            if (buffType == "Enrage" or buffType == "")then -- apparently enrages are empty string (still true?)
                if aura == "Enrage" then
                    if ragingPurgeList[name] then
                        dispelScore = dispelScore + 1
                    end
                elseif aura == "Painful Motivation" then
                    print('not dispelling with painful motivation')
                    return
                else
                    dispelScore = dispelScore + 1
                end

            end

        end
        if dispelScore > 0 then
            return true
        end
    else
        return true
    end
end