---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "The Nokhud Offensive"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if (unit:AuraRemaining("Seal Empowerment", "HELPFUL") > 0) then
        print('not dpsing with Seal Empowerment buff')
        return true
    elseif unit.name == "Stormsurge Totem" then
        if unit.health <= 1 then
            return true
        end
    end

    return WGBM.default.Priority(spell, unit, args)
end

WGBM[bossString].Priority = function(spell, unit, args)
    if unit.name == "Stormsurge Totem" then
        return 20
    end

    return WGBM.default.Priority(spell, unit, args)
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    if unit.name == "Stormsurge Totem" then return true end
end

WGBM[bossString].AoeBlacklisted = function(spell, unit, args)
    local name = unit.name
    if name == "Explosives" then
        return true
    elseif name == "Stormsurge Totem" then
        return true
    end
end