---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Azure Vault"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local name = unit.name
    if (unit:AuraRemaining("Seal Empowerment", "HELPFUL") > 0) then
        print('not dpsing with Seal Empowerment buff')
        return true
    end

    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

--
WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if name == "Depraved Mistweaver" then
        local cast = UnitCastingInfo(unitid)
        print('Curator')
        if cast == "Heavy Tome" then
            -- only interrupt if the target is low health
            return (UnitHealth(unitid .. "target") or 0) / (UnitHealthMax(unitid .. "target") or 1) < 0.5
        end
        return
    elseif name == "Arcane Elemental" then
        local cast = UnitCastingInfo(unitid)
        if cast == "Arcane Bolt" then
            -- only interrupt if the target is low health
            return (UnitHealth(unitid .. "target") or 0) / (UnitHealthMax(unitid .. "target") or 1) < 0.5
        elseif cast == "Waking Bane" then
            return true
        end
        return
    end
    return true
end