---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Decatriarch Wratheye"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local name = unit.name
    if (unit:AuraRemaining("Seal Empowerment", "HELPFUL") > 0) then
        print('not dpsing with Seal Empowerment buff')
        return true
    end
    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return false
end

WGBM[bossString].DotBlacklisted = function(spell, unit, args)

end

WGBM[bossString].AoeBlacklisted = function(spell, unit, args)
    if unit.name == "Explosives" then
        return true
    end
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Priority = function(spell, unit, args)
    local name = unit.name
    local unitid = unit.unitid
    local score = 10
    if name == "Rotburst Totem" then
        score = 20
    end
    if UnitIsUnit("target", unitid) then
        score = score + 5
    end
    return score, bossString
end