---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Brackenhide Hollow"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local name = unit.name
    if (unit:AuraRemaining("Seal Empowerment", "HELPFUL") > 0) then
        print('not dpsing with Seal Empowerment buff')
        return true
    end
    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].DotBlacklisted = function(spell, unit, args)

end

WGBM[bossString].AoeBlacklisted = function(spell, unit, args)
    if unit.name == "Explosives" then
        return true
    end
end

WGBM[bossString].Priority = function(spell, unit, args)
    local name = unit.name
    local unitid = unit.unitid
    local score = 10
    if strmatch(name, "Totem$") then
        score = 40
    end
    if UnitIsUnit("target", unitid) then
        score = score + 5
    end
    return score, bossString
end

WGBM[bossString].CleansePriority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 0
    for i=1,40 do
        local name, icon, count, buffType, duration, expiresAt, unitCaster = UnitDebuff(unitid, i)
        if name == nil or name == "" then
            break
        end
        if (WarGod.Unit:GetPlayer().dispellableauratypes[buffType])then
            if (not count) or count == 0 then count = 1 end
            score = score + count
        end
    end
    local role = UnitGroupRolesAssigned(unitid)
    if role == "TANK" then
        return score * 0.5
    end
    if UnitIsUnit(unitid, "player") then
        return score * 1.2
    end
    if role == "HEALER" then
        return score * 0.8
    end
    local class = UnitClass(unitid)
    if class == "Hunter" then
        return score
    end
    return score * 0.9
end