---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Ring of Booty"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    --print('boo')
    if (strmatch(unit.name, "Shark")) then
        printTo(3,'not dpsing sharks')
        return true
    end
    local name = unit.name
    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return false
end

WGBM[bossString].Interrupt = function(spell, unit, args)

    return true
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    return 1337

end