---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods
local WarGodUnit = WarGod.Unit
local bossString = "Gunker"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if unit.name ~= bossString and unit.name ~= "Goop" and unit.name ~= "Gooped" then
        return true
    elseif unit.name == "Walkie Shockie X1" then
        return true
    end
    return false
end

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    if unit.name == "Explosives" then
        return true
    end
end