---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "HK-8 Aerial Oppression Unit"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    --print('boo')
    if UnitGroupRolesAssigned("player") == "TANK" then
        return
    end
    local remains, stacks = unit:AuraRemaining("Force Shield", "HELPFUL")
    if stacks > 0 then
        return true
    elseif unit.name == "Walkie Shockie XI" then
        return true
    end

    return false
end

WGBM[bossString].Priority = function(spell, unit, args)
    --print('default priority')
    --local unitid = unit.unitid
    --local name = unit.name
    local remains, stacks = unit:AuraRemaining("Platinum Plating", "HELPFUL")
    return 10 - stacks
end

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name ~= bossString) then
        return true
    end
end

WGBM[bossString].Mitigation = function(spell, unit, args)
    --print('fetid mitigation')
    local bossThreat = UnitThreatSituation("player","boss1")
    if bossThreat and bossThreat >= 3 then
        if UnitChannelInfo("boss1") == "Wreck" or UnitCastingInfo("boss1") == "Wreck" then
            return true
        end
    end
end