---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "K.U.-J.O."
printTo(3,bossString)
WGBM[bossString] = {}


WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    --print('boo')
    if UnitGroupRolesAssigned("player") == "TANK" then
        return
    end
    local remains, stacks = unit:AuraRemaining("Platinum Plating", "HELPFUL")
    if stacks > 2 then
        return true
    end

    return false
end

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name ~= bossString) then
        return true
    end
end

WGBM[bossString].Mitigation = function(spell, unit, args)
    --print('fetid mitigation')
    local bossThreat = UnitThreatSituation("player","boss1")
    --local bossCasting = UnitCastingInfo("boss1")
    if bossThreat and bossThreat >= 3 then
        if WarGod.Unit:GetPlayer():DebuffRemaining("Blazing Chomp", "HARMFUL") > 0 then
            return true
        end
    end
end