---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Nhallish"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if (unit:AuraRemaining("Water Bubble", "HELPFUL") > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    end

    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    --[[if UnitCastingInfo(unitid) == "Bone Spike" then
        return
    end]]
    --print('cos interrupt')
    if name == "Shadowmoon Exhumer" then
        if UnitCastingInfo(unitid) == "Void Bolt" then
            return (UnitHealth(unitid .. "target") or 0) / (UnitHealthMax(unitid .. "target") or 1) < 0.5
        end
        return
    elseif name == "Shadowmoon Dominator" then
        if UnitCastingInfo(unitid) == "Domination" then
            return UnitIsFriend(unitid .. "target", "player")

        end
        return
    end
    return true
end