---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Ner'zhul"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    --[[if (unit:AuraRemaining("Water Bubble", "HELPFUL") > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    end]]

    if unit.name == "Ritual of Bones" then
        if UnitIsUnit(unit.unitid,"target") or GetRaidTargetIndex(unit.unitid) == 8 then
            return
        end
        return true
    end


    return
end

--[[WGBM[bossString].Priority = function(spell, unit, args)
    --print('default priority')
    local unitid = unit.unitid
    local name = unit.name
    local score = 10

    return score, bossString
end]]

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]