---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Wise Mari"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if (unit:AuraStacks("Water Bubble", "HELPFUL") >= 4) then
        printTo(3,'not dpsing with 4 Bubble buffs')
        return true
    end

    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 0
    local name = unit.name
    if name == "Corrupt Living Water" then
        score = 20
    elseif name == "Wise Mari" then
        score = 10
    end

    if UnitIsUnit(unitid, "target") then
        score = score + 5
    end
    return score, bossString
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name

    if name == bossString then
        if UnitClass("player") == "Druid" and GetSpecialization() == 2 then
            if WarGod.Unit:GetPlayer():DebuffRemaining("Corrupted Vortex","HARMFUL") > 0 then
                print("not interrupting during vortex")
                return
            end
        end
    end
    return true
end