---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Rokmora"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    local unitid = unit.unitid
    --if UnitAffectingCombat(unitid) then return end  -- hoping this lets through the things that are fighting at the entrance
    local name = unit.unitid
    if WarGod.Control:SafeMode() then
        if UnitIsUnit(unitid, "mouseover") or UnitIsUnit(unitid, "target") then
            return
        end
        return true
    end


    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Priority = function(spell, unit, args)
    --if spell ~= "" then print('default priority') end
    local unitid = unit.unitid
    local name = unit.name
    local score = 10
    --print(unitid)
    --[[if (unit.name == "Explosives") then
        return 1000000, "default"
    elseif unit.health_percent < 0.95 and unit:BuffRemaining("Inspiring Presence", "HELPFUL") > 0 then
        return 5000, "default"
    end]]
    if name ~= bossString then
        score = 50
    end

    if UnitIsUnit("target", unitid) then
        score = score + 5
    end

    return score, bossString
end

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    local name = unit.name
    if name ~= bossString then
        return true
    end
    return
end

WGBM[bossString].Defensive = function(spell, unit, args)
    local cast = UnitCastingInfo("boss1")
    if cast == "Shatter" and WarGod.Unit.active_enemies > 1 then
        return true
    end
end

WGBM[bossString].BurstUnit = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if name ~= bossString then
        if UnitCastingInfo("boss1") == "Shatter" then
            return true
        end
    end
end


