---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Ularogg Cragshaper"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    local unitid = unit.unitid
    --if UnitAffectingCombat(unitid) then return end  -- hoping this lets through the things that are fighting at the entrance
    local name = unit.unitid
    if WarGod.Control:SafeMode() then
        if UnitIsUnit(unitid, "mouseover") or UnitIsUnit(unitid, "target") then
            return
        end
        return true
    end


    if name == "Incorporeal Being" then return true end
    if WarGod.Rotations.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return
end
--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 10
    local name = unit.name
    if name == "Bellowing Idol" then
        score = 30
        --if unit:BuffRemaining("Flame Shield","HELPFUL") > 0 then
        --end
    else
    end

    if UnitIsUnit("target", unitid) then
        score = score + 5
    end
    return score
end

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    local name = unit.name
    if name == "Bellowing Idol" then
        if unit.health_percent < 0.9 then
            return true
        end
    elseif name == "Incorporeal Being" then
        return true
    end
end

WGBM[bossString].AoeBlacklisted = function(spell, unit, args)
    local name = unit.name
    if name == "Bellowing Idol" and (not UnitExists("boss1")) then
        return true
    end
end