---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Naraxas"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    local unitid = unit.unitid
    --if UnitAffectingCombat(unitid) then return end  -- hoping this lets through the things that are fighting at the entrance
    local name = unit.unitid
    if WarGod.Control:SafeMode() then
        if UnitIsUnit(unitid, "mouseover") or UnitIsUnit(unitid, "target") then
            return
        end
        return true
    end


    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return
end

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    return true
end

WGBM[bossString].Priority = function(spell, unit, args)
    --if spell ~= "" then print('default priority') end
    local unitid = unit.unitid
    local name = unit.name
    local score = 10
    --print(unitid)
    --[[if (unit.name == "Explosives") then
        return 1000000, "default"
    elseif unit.health_percent < 0.95 and unit:BuffRemaining("Inspiring Presence", "HELPFUL") > 0 then
        return 5000, "default"
    end]]
    if name ~= bossString then
        score = 50
    end

    if UnitIsUnit("target", unitid) then
        score = score + 5
    end

    return score, bossString
end

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    local name = unit.name
    if name ~= bossString then
        if spell == "Moonfire" and unit.health_percent > 0.90 then
            return
        elseif spell == "Sunfire" and unit.health_percent > 0.99 then
            return
        end
        return true
    end
    return
end

WGBM[bossString].CleansePriority = function(spell, unit, args)
    local unitid = unit.unitid
    local role = UnitGroupRolesAssigned(unitid)
    local class = UnitClass(unitid)
    if UnitIsUnit("player", unitid) then
        return 10
    end
    if 1==1 then return 0 end
    if role == "TANK" then
        return 1
    elseif class == "Rogue" or class == "Death Knight" or class == "Warrior" or class == "Demon Hunter" or class == "Paladin" or class == "Monk" then
        return 3
    elseif role == "HEALER" then
        return 6
    else
        return 7
    end
end