---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Neltharion's Lair"
print(bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    local unitid = unit.unitid
    --if UnitAffectingCombat(unitid) then return end  -- hoping this lets through the things that are fighting at the entrance
    local name = unit.unitid
    if WarGod.Control:SafeMode() then
        if UnitIsUnit(unitid, "mouseover") or UnitIsUnit(unitid, "target") then
            return
        end
        return true
    end


    if name == "Incorporeal Being" then return true end
    if WarGod.Rotations.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    --[[if UnitCastingInfo(unitid) == "Bone Spike" then
        return
    end]]
    --print('cos interrupt')
    if name == "Guardian Construct" then
        if UnitCastingInfo(unitid) == "Charging Station" then
            return
        end
    elseif name == "Baalgar the Watchful" then
        -- only going to interrupt the channel
        if UnitCastingInfo(unitid) ~= nil then
            return
        end
    end
    return true
end


WGBM[bossString].Purge = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    local class = UnitClass("player")
    if class == "Druid" or class == "Hunter" or class == "Rogue" then
        local dispelScore = 0
        for i=1,40 do
            local aura, icon, count, buffType, duration = UnitBuff(unitid, i)
            if not aura then return end--if (buffType) then print(buffType) end
            if (buffType == "Enrage" or buffType == "")then -- apparently enrages are empty string (still true?)
                if aura == "Enrage" then
                    if name "Rockback Gnasher" or
                        --name == "Tarspitter Lurker" or    -- probably only want this in a group with grips
                        name == "Understone Drummer" or
                        --name == "Blightshard Shaper" or
                        --name == "Rockbound Trapper" or
                        name == "Rockbound Pelter" then
                        dispelScore = dispelScore + 1
                    end
                else
                    dispelScore = dispelScore + 1
                end
                if dispelScore > 0 then
                    return true
                end
            end

        end
    else
        return true
    end
end