---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Priestess Alun'za"
printTo(3,bossString)
WGBM[bossString] = {}
--[[
WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    --if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    --else--if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Runic Ward buff')
        return true

    --else--if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Ironbark Shield buff')
        return true
    end

    return false
end]]

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end