---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods
local WarGodUnit = WarGod.Unit
local bossString = "Vol'kaal"
printTo(3,bossString)
WGBM[bossString] = {}
--[
WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    if (unit:AuraRemaining("Bad Voodoo", "HELPFUL") > 0 and UnitGroupRolesAssigned("player") ~= "TANK") then
        printTo(3,'not dpsing with Bad Voodoo buff')
        return true
    elseif unit.name == "Reanimation Totem" then
        if UnitIsUnit("target", unitid) then
            return
        end
        if WarGodUnit:GetTarget().health_percent > unit.health_percent + 0.1 then
            return true
        end
    end

    return false
end

WGBM[bossString].DotBlacklisted = function(spell, unit, args)
    if unit.name == "Explosives" then
        return true
    end
end