---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "The Underrot"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if WarGod.Control:SafeMode() then
        if UnitIsUnit(unitid, "mouseover") or UnitIsUnit(unitid, "target") then
            return
        end
        return true
    end


    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    if (name == "Spirit Drain Totem") then
        return true
    elseif unit:BuffRemaining("Infested", "HELPFUL") > 0 then
        if not UnitIsUnit("target", unitid) then
            return true
        end
    end

    return false
end


WGBM[bossString].ExtraHealthMissing = function(spell, unit, args)
    local total = 0
    local unitid = unit.unitid
    for i = 1, 5 do
        local debuffName = UnitDebuff(unitid,i)
        if not debuffName then
            break
        end
        if debuffName == "Decaying Mind" then
            local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2
        end
    end
    return total
    --local debuffName, _, _, _, _, _, _, _,_,_,_,_,_, _, _,absorbAmount = UnitDebuff("player",i)=="Immunosuppression"
    --/run for i=1,5 do if UnitDebuff("player",i)=="Immunosuppression" then print(select(16, UnitDebuff("player",i))) end end
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    --[[if unit.name == "Azsh'ari Witch" then
        return true
    end]]
    if unit.name == "Grotesque Horror" then
        if UnitCastingInfo(unit.unitid) == "Void Spit" then
            return
        end
    end
    return true
end

WGBM[bossString].CleansePriority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 0
    for i=1,40 do
        local name, icon, count, buffType, duration, expiresAt, unitCaster = UnitDebuff(unitid, i)
        if name == nil or name == "" then
            break
        end
        if (WarGod.Unit:GetPlayer().dispellableauratypes[buffType])then
            if (not count) or count == 0 then count = 1 end
            score = score + count
        end
    end
    local role = UnitGroupRolesAssigned(unitid)
    if role == "TANK" then
        return score * 0.5
    end
    if UnitIsUnit(unitid, "player") then
        return score * 1.2
    end
    if role == "HEALER" then
        return score * 0.8
    end
    local class = UnitClass(unitid)
    if class == "Hunter" then
        return score
    end
    return score * 0.9
end