---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "The Sand Queen"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid


    return false
end

WGBM[bossString].Purge = function(spell, unit, args)
    local remains, stacks = unit:DebuffRemaining("Enrage", "HELPFUL")
    if stacks < 4 or remains < 2 then
        return
    end
    return true
end