---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Jes Howlis"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid


    return
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local casting = UnitCastingInfo(unitid)
    if not casting then
        casting = UnitChannelInfo(unitid)
    end
    if casting == "Howling Fear" then
        return true
    elseif casting == "Vicious Mauling" then
        return true
    end
end