---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Overseer Korgus"
printTo(3,bossString)
WGBM[bossString] = {}

--[[WGBM[bossString].DPSBlacklist = function(spell, unit, args)
--    local unitid = unit.unitid
    --if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        --printTo(3,'not dpsing with Soul Armor buff')
        return true
    end

    return false
end]]

WarGod.BossMods[bossString].Preheal = function(spell, unit, args)
    local unitid = unit.unitid
    print("keeping bubbles on everyone")
    return true
end