---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "The Stonevault"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    local name = unit.name

    if name == "Incorporeal Being" then return true end
    --
    if name == "Cursedheart Invader" or
            "Earth Infused Golem" or
            "Ghastly Voidsoul" or
            "Repurposed Loaderbot" or
            "Void Bound Despoiler" or
            "Engine Speaker" or
            "Injured Earthen" then
        if (not C_UnitAuras.GetDebuffDataByIndex(unit.unitid, 2)) and (not UnitIsPlayer(unit.unitid .. "target")) then return true end
    end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local score = 10
    local name = unit.name
    if name == "Earth Burst Totem" then
        score = 50
    end
    if UnitIsUnit(unitid, "target") then
        score = score + 5
    end
    return score, bossString
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local name = unit.name
    if name == "Spectral Invoker" then
        if UnitCastingInfo(unit.unitid) == "Astral Bomb" then
            return
        end
    end
    return true
end

WGBM[bossString].BurstUnit = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if name == "Grim Reflection" then
        return true
    elseif name == "Monstrous Soul" then
        if unit.health_percent < 0.4 then
            return true
        elseif UnitCastingInfo(unitid) == explosionName or UnitChannelInfo(unitid) == explosionName then
            return true
        end
    end

    return false
end