---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Adderis and Aspix"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    if (unit:AuraRemaining("Lightning Shield", "HELPFUL") > 0) then
        --print('not dpsing with Lightning Shield buff')
        return true
    --[[elseif UnitCastingInfo(unitid) == "Lightning Shield" then
        return true
    elseif UnitChannelInfo(unitid) == "Lightning Shield" then
        return true]]
    else
        if UnitCastingInfo("boss1") == "Lightning Shield" then
            return true
        elseif UnitCastingInfo("boss2") == "Lightning Shield" then
            return true
        end
    end

    return false
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    return 1337
end