---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Galvazzt"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid


    return false
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    return 1337

end