---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Avatar of Sethraliss"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid


    return false
end

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid

    local name = unit.name
    if (name == "Hoodoo Hexer") then
        if UnitChannelInfo(unitid) == "Taint" then
            return true
        else
            return
        end
    elseif (name == "Plague Toad") then
        return true
    end

    return false
end

-- when boss has "Life Force" put every hot on it
WGBM[bossString].FriendlyBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    if (unit:AuraRemaining("Taint", "HELPFUL") > 0) then
        --printTo(3,'not dpsing with Soul Armor buff')
        return true
    end

    return false
end

WGBM[bossString].CleansePriority = function(spell, unit, args)
    local unitid = unit.unitid
    local role = UnitGroupRolesAssigned(unitid)
    local class = UnitClass(unitid)
    local playerClass = UnitClass("player")
    if playerClass == "Priest" or playerClass == "Monk" or playerClass == "Paladin" then
        if role == "HEALER" then
            return 5
        elseif role == "TANK" and (class == "Paladin" or class == "Druid" or class == "Death Knight" or class == "Demon Hunter") then
            return 4
        else
            if class == "Druid" or class == "Monk" or class == "Priest" or class == "Shaman" or class == "Paladin" then
                return 3
            end
            return 2 - unit.health_percent
        end
    end
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    local aoeIn = 1337
    local now = GetTime()
    for msg,time in pairs(WGBM.timers) do
        local timeDiff = time - now
        if timeDiff < aoeIn and timeDiff > -5 then
            if strmatch(msg, "Heart Guardian") then
                aoeIn = timeDiff + 3
            end
        end
    end
    return aoeIn

end