---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Temple of Sethraliss"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    if (unit:AuraRemaining("Dust Cloud", "HARMFUL") > 0) then
        printTo(3,'not dpsing while obscured buff')
        return true
    --[[elseif unit:BuffRemaining("Infested", "HELPFUL") > 0 then
        if not UnitIsUnit("target", unitid) then
            return true
        end]]
    elseif unit:BuffRemaining("Lightning Shield", "HELPFUL") > 0 then
        return true
    end


    return false
end

WGBM[bossString].Cleanse = function(spell, unit, args)
    local unitid = unit.unitid
    if UnitClass("player") == "Druid" or UnitClass("player") == "Mage" then
        if unit:BuffRemaining("Unstable Hex", "HARMFUL") > 0 then
            return
        elseif unit:BuffRemaining("Neurotoxin", "HARMFUL") > 0 then
            if UnitIsUnit(unitid, "player") then
                return true
            elseif GetUnitpeed(unitid) > 0 then
                return true
            elseif UnitGroupRolesAssigned(unitid) == "TANK" then
                return true
            end
            for i=1,4 do
                local name, icon, count, debuffType, duration = UnitDebuff(unitid, i)
                if (name == nil) then break end
                if name == "Neurotoxin" then
                    if duration > 4.5 then
                        return true
                    end
                end
            end
        end
    end

    return true
end
