---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Chopper Redhook"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if name == "Chopper Redhook" then
        return
    end
    if ((WarGod.Control:AOEDotEnabled() or WarGod.Control:SafeMode()) and (not UnitIsUnit("target", unitid))) then
        return true
    end
end

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name ~= bossString) then
        return true
    end
end

WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    --if (addSoon and WarGodU)
    local score = 10
    if name ~= bossString then
        score = 20
    elseif unit:BuffRemaining("Heavy Ordnance", "HELPFUL") > 0 then
        score = 21
    elseif unit:BuffRemaining("Heavy Ordnance", "HARMFUL") > 0 then
        score = 21
    end
    if UnitIsUnit(unitid, "target") then
        score = score + 5
    end
    return score, bossString
    --return WGBM.default.Priority(spell, unitid, args)
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    return true
end