---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Court of Stars"
print(bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if (unit:AuraRemaining("Water Bubble", "HELPFUL") > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    end

    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    --[[if UnitCastingInfo(unitid) == "Bone Spike" then
        return
    end]]
    --print('cos interrupt')
    if name == "Guardian Construct" then
        if UnitCastingInfo(unitid) == "Charging Station" then
            return
        end
    elseif name == "Baalgar the Watchful" then
        -- only going to interrupt the channel
        if UnitCastingInfo(unitid) ~= nil then
            return
        end
    end
    return true
end