---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Watcher Irideus"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local name = unit.name
    if (unit:AuraStacks("Ablative Barrier", "HELPFUL") > 2) then     -- stacks probably matters more
        print('not dpsing with Ablative Barrier buff')
        return true
    elseif unit.health < 5 then
        return true
    end
    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end

    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]