---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Halls of Infusion"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    local unitid = unit.unitid
    --if UnitAffectingCombat(unitid) then return end  -- hoping this lets through the things that are fighting at the entrance
    local name = unit.unitid

    if name == "Incorporeal Being" then return true end
    if WarGod.Rotation.Delegates:UnitIsBreakableCrowdControlled(spell, unit, args) then return true end
    if name == "Primalist Ravager" or name == "Primalist Geomancer" or name == "Primalist Defender" or name == "Containment Apparatus" then -- mobs fighting at entrance
        --if unit.health_percent < 0.80 then return end
        --if UnitThreatSituation(unitid .. "target", unitid) then return end
        if UnitExists(unitid.."target") and UnitIsPlayer(unitid .. "target") then return end
        if UnitDebuff(unitid, 3) then return end
        return true
    end
    if name == "Watcher Irideus" then
        if UnitAffectingCombat(unitid) then return end
        return true
    end

    return
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].Cleanse = function(spell, unit, args)
    local toxinStacks = unit:AuraStacks("Gulp Swog Toxin", "HARMFUL")
    if toxinStacks > 6 then
        return true
    elseif toxinStacks > 0 then
        return
    else
        return true
    end
end