---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Zekvir (Tier 1)"
printTo(3,bossString)
WGBM[bossString] = {}


WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local name = unit.name
    return false
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]

WGBM[bossString].BurstUnit = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    print("burst")
    if name == "Egg Cocoon" then
        return true
    end

    --return false
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    local theTime = GetTime()
    local spell, displayName, icon, startTime, endTime, isTradeSkill, notInterruptible = UnitCastingInfo (unitid)
    if (spell == "Enfeebling Spittle") then
        return
    else
        return true
    end
end

local altName = "Zekvir (Tier 2)"
WGBM[altName] = WGBM[bossString]