---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Kokia Blazehoof"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    --print('boo')
    if unit.name == "Blazebound Firestorm" and UnitCastingInfo(unit.unitid) == "Burnout" then
        return true
    end

    return false
end

WGBM[bossString].Mitigation = function(spell, unit, args)
    --print('fetid mitigation')
    local bossCasting = UnitCastingInfo("boss1")
    local bossChannel = UnitChannelInfo("boss1")
    --if UnitIsUnit("boss1target", "player") then
    if bossChannel == "Searing Wounds" then
        local bossThreat = UnitThreatSituation("player","boss1")
        if not bossThreat or bossThreat < 3 then
            return true
        end
    end
    --end
    --return score, bossString
end

--[[WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name == "Spirit of Gold") then
        return true
    end
end]]