---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 11/09/2018 9:34 PM
---

local WGBM = WarGod.BossMods

local Rotations = WarGod.Rotation
local Class = WarGod.Class
local groups = WarGod.Unit.groups
local player = WarGod.Unit:GetPlayer()
local talent = player.trait
local buff = player.buff
local azerite = player.azerite
local WarGodUnit = WarGod.Unit
local WarGodControl = WarGod.Control


local upairs = upairs

---------TEMP-------------
local WGBM = WarGod.BossMods
--local Delegates = Rotations.Delegates
--------------------------

setfenv(1, Rotations)


do
    local baseScore = 90000
    --[[do
        local nonFeralSpecs = {"Balance", "Guardian", "Restoration"}
        for _,spec in pairs(nonFeralSpecs) do
            AddSpellFunction(spec,"Nothing",baseScore,{
                -- using stacks because it avoids checking a function
                func = function(self) return buff.cat_form:Stacks() > 0
                end,
                units = groups.noone,
                label = "Stay in Cat Form"
            })

        end

    end]]

end