---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 11/09/2018 9:34 PM
---

local WGBM = WarGod.BossMods

local Rotations = WarGod.Rotation
local Class = WarGod.Class
local groups = WarGod.Unit.groups
local player = WarGod.Unit:GetPlayer()
local talent = player.trait
local buff = player.buff
local azerite = player.azerite
local WarGodUnit = WarGod.Unit
local WarGodControl = WarGod.Control


local upairs = upairs
local select = select

local GetShapeshiftForm = GetShapeshiftForm
local GetShapeshiftFormInfo = GetShapeshiftFormInfo

---------TEMP-------------
local WGBM = WarGod.BossMods
--local Delegates = Rotations.Delegates
--------------------------

setfenv(1, Rotations)


local baseScore = 100000
do
    AddSpellFunction(nil,"Nothing",100000,{
        -- using stacks because it avoids checking a function
        func = function(self)
            local formIndex = GetShapeshiftForm()
            if formIndex == 3 then
                return true
            end
            if formIndex >= 4 and formIndex <= 6 then
                if select(4, GetShapeshiftFormInfo(formIndex)) == 210053 then
                    return true
                end
            end
        end,
        units = groups.noone,
        label = "Stay in Travel Form"
    })

end