---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Adoredris.
--- DateTime: 5/08/2018 2:42 PM
---

--- reserves all the binds that the default UI has bound crap to (hopefully) as well as some manually defined things

setfenv(1, Sky.Binder)

--[[local ]]reservedBinds = {}
function IsReserved(keybind)
    local containsAlt = strmatch(keybind,"ALT")
    local containsShift = strmatch(keybind,"SHIFT")
    local containsCtrl = strmatch(keybind,"CTRL")
    local baseKey = keybind
    if containsAlt ~= nil or containsShift ~= nil or containsCtrl ~= nil then
        baseKey = strrev(strsub(strrev(keybind), 1, strfind(strrev(keybind), "-")-1))
    end
    if (reservedBinds[baseKey]) then
        local text = (containsAlt and "ALT" or "") .. (containsCtrl and "CTRL" or "") .. (containsShift and "SHIFT" or "")
        --[[if not containsAlt and not containsCtrl and not containsShift then
            print(keybind)
        end]]
        if (reservedBinds[baseKey][text]) then
            --print(keybind .. " is reserved")
            return true
        end

    end
    --[[local containsAlt = strmatch(keybind,"ALT")
    local containsShift = strmatch(keybind,"SHIFT")
    local containsCtrl = strmatch(keybind,"CTRL")
    local baseKey = keybind
    if containsAlt ~= nil or containsShift ~= nil or containsCtrl ~= nil then
        baseKey = strrev(strsub(strrev(keybind), 1, strfind(strrev(keybind), "-")-1))
    end
    for k,v in pairs(reservedBinds) do
        if (containsAlt and strmatch(keybind, "ALT") or not containsAlt and not strmatch("ALT")) then
            if (containsAlt and strmatch(keybind, "ALT") or not containsAlt and not strmatch("ALT")) then
        end
    end]]

end

function ReserveBind(keybind)
    local containsAlt = strmatch(keybind,"ALT")
    local containsShift = strmatch(keybind,"SHIFT")
    local containsCtrl = strmatch(keybind,"CTRL")
    local baseKey = keybind
    if containsAlt ~= nil or containsShift ~= nil or containsCtrl ~= nil then
        baseKey = strrev(strsub(strrev(keybind), 1, strfind(strrev(keybind), "-")-1))
    end
    if (not reservedBinds[baseKey]) then reservedBinds[baseKey] = {} end
    local text = (containsAlt and "ALT" or "") .. (containsCtrl and "CTRL" or "") .. (containsShift and "SHIFT" or "")
    reservedBinds[baseKey][text] = true
end


ReserveBind ("RALT-F4")
ReserveBind ("LALT-F4")
ReserveBind ("LSHIFT-`")
ReserveBind ("RSHIFT-`")

ReserveBind ("RSHIFT-F")
ReserveBind ("LSHIFT-F")

ReserveBind ("SHIFT-C")



--ReserveBind ("LCTRL")
--ReserveBind ("RCTRL")
--ReserveBind ("LSHIFT")
--ReserveBind ("RSHIFT")
--ReserveBind ("LALT")
--ReserveBind ("RALT")

ReserveBind ("F1") -- F1 is interact with target
ReserveBind ("F2")
ReserveBind ("F3")
ReserveBind ("F4")
ReserveBind ("F5")
ReserveBind ("F6")
ReserveBind ("F7")
ReserveBind ("F8")
ReserveBind ("F9")
ReserveBind ("F10")
ReserveBind ("F11")
ReserveBind ("F12")
ReserveBind ("0")
ReserveBind ("1")
ReserveBind ("2")
ReserveBind ("3")
ReserveBind ("4")
ReserveBind ("5")
ReserveBind ("6")
ReserveBind ("7")
ReserveBind ("8")
ReserveBind ("9")
ReserveBind ("A")
ReserveBind ("B")
ReserveBind ("C")
ReserveBind ("D")
ReserveBind ("E")
ReserveBind ("F")
ReserveBind ("G")
ReserveBind ("H")
ReserveBind ("I")
ReserveBind ("J")
ReserveBind ("K")
ReserveBind ("L")
ReserveBind ("M")
ReserveBind ("N")
ReserveBind ("O")
ReserveBind ("P")
ReserveBind ("Q")
ReserveBind ("R")
ReserveBind ("S")
ReserveBind ("T")
ReserveBind ("U")
ReserveBind ("V")
ReserveBind ("W")
ReserveBind ("X")
ReserveBind ("Y")
ReserveBind ("Z")
ReserveBind ("`")
ReserveBind ("[")
ReserveBind ("]")
ReserveBind ("'")
ReserveBind (",")
ReserveBind (".")
ReserveBind ("/")
ReserveBind ("=")
ReserveBind ("\\")
ReserveBind ("-")
ReserveBind (";")

ReserveBind ("CTRL-G")
ReserveBind ("ALT-G")
ReserveBind ("ALT-F")
ReserveBind ("SHIFT-G")

-- lee stuff --
--[[ReserveBind("LALT-LSHIFT-F1")
ReserveBind("RALT-RSHIFT-F1")
ReserveBind("LALT-RSHIFT-F1")

ReserveBind("ALT-CTRL-SHIFT-;")
ReserveBind("ALT-CTRL-SHIFT-'")
ReserveBind("ALT-SHIFT-M")
ReserveBind("ALT-SHIFT-F")
ReserveBind("ALT-CTRL-SHIFT-F")
ReserveBind("ALT-CTRL-SHIFT-B")
ReserveBind("ALT-CTRL-SHIFT-G")
ReserveBind("ALT-SHIFT-R")
ReserveBind("SHIFT-Q")
ReserveBind("SHIFT-E")
ReserveBind("CTRL-Q")
ReserveBind("CTRL-E")
ReserveBind("CTRL-A")
ReserveBind("CTRL-D")
--ReserveBind("R")
--ReserveBind("Z")
ReserveBind("CTRL-SHIFT-A")
ReserveBind("ALT-CTRL-N")
ReserveBind("ALT-CTRL-F")
ReserveBind("ALT-SHIFT-N")
ReserveBind("SHIFT-V")
ReserveBind("ALT-SHIFT-I")]]		-- invite team

ReserveBind("SHIFT-1")
ReserveBind("SHIFT-2")
ReserveBind("SHIFT-3")
ReserveBind("SHIFT-4")
ReserveBind("SHIFT-5")
ReserveBind("SHIFT-6")
ReserveBind("SHIFT-7")
ReserveBind("SHIFT-8")
ReserveBind("SHIFT-9")
ReserveBind("SHIFT-0")
ReserveBind("SHIFT--")
ReserveBind("SHIFT-=")
--[[
ReserveBind ("CTRL-SHIFT-F2")

ReserveBind("ALT-CTRL-SHIFT-;")
ReserveBind("ALT-CTRL-SHIFT-'")]]