---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Mchimba the Embalmer"
printTo(3,bossString)
WGBM[bossString] = {}
--[[
WGBM[bossString].DPSBlacklist = function(spell, unit, args)     local unitid = unit.unitid
    local unitid = unit.unitid
    --print('boo')
    --if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    --else--if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Runic Ward buff')
        return true

    --else--if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Ironbark Shield buff')
        return true
    end

    return false
end]]

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name ~= bossString) then
        return true
    end
end

WGBM[bossString].ExtraHealthMissing = function(spell, unit, args)
    local total = 0
    local unitid = unit.unitid
    for i = 1, 5 do
        local debuffName = UnitDebuff(unitid,i)
        if not debuffName then
            break
        end
        if debuffName == "Wretched Discharge" then
            --local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2

        end
    end
    return total
    --local debuffName, _, _, _, _, _, _, _,_,_,_,_,_, _, _,absorbAmount = UnitDebuff("player",i)=="Immunosuppression"
    --/run for i=1,5 do if UnitDebuff("player",i)=="Immunosuppression" then print(select(16, UnitDebuff("player",i))) end end
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    return 1337
end