---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ikevink.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "The Council of Tribes"
printTo(3,bossString)
WGBM[bossString] = {}
--[[
WGBM[bossString].DPSBlacklist = function(spell, unit, args)
    local unitid = unit.unitid
    --print('boo')
    --if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Soul Armor buff')
        return true
    --else--if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Runic Ward buff')
        return true

    --else--if (unit:AuraRemaining(.+, unit, "HELPFUL) > 0) then
        printTo(3,'not dpsing with Ironbark Shield buff')
        return true
    end

    return false
end]]

WGBM[bossString].DPSWhitelist = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    if (name ~= bossString) then
        return true
    end
end

WGBM[bossString].ExtraHealthMissing = function(spell, unit, args)
    local total = 0
    local unitid = unit.unitid
    for i = 1, 5 do
        local debuffName = UnitDebuff(unitid,i)
        if not debuffName then
            break
        end
        if debuffName == "Severing Axe" then
            --local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2
        elseif debuffName == "Whirling Axe" then
            --local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2
        end
    end
    return total
    --local debuffName, _, _, _, _, _, _, _,_,_,_,_,_, _, _,absorbAmount = UnitDebuff("player",i)=="Immunosuppression"
    --/run for i=1,5 do if UnitDebuff("player",i)=="Immunosuppression" then print(select(16, UnitDebuff("player",i))) end end
end

WGBM[bossString].Mitigation = function(spell, unit, args)
    --print('fetid mitigation')
    local bossCasting = UnitCastingInfo("boss1")
    --if UnitIsUnit("boss1target", "player") then
    if bossCasting == "Debilitating Backhand" then
        local bossThreat = UnitThreatSituation("player","boss1")
        if bossThreat and bossThreat >= 3 then
            return true
        end
    end
    --end
    --return score, bossString
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    if UnitCastingInfo(unitid) == "Lightning Bolt" then
        return
    end
    return true
    --printTo(3,'default interrupt')
end

WGBM[bossString].Purge = function(spell, unit, args)
    if UnitIsUnit(unit.unitid, "target") then
        return true
    end
    return
end

WGBM[bossString].AoeIn = function(spell, unit, args)
    return 1337
end