---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Flora.
--- DateTime: 15/08/2018 11:07 PM
---

local WGBM = WarGod.BossMods

local bossString = "Kings' Rest"
printTo(3,bossString)
WGBM[bossString] = {}

WGBM[bossString].Priority = function(spell, unit, args)
    local unitid = unit.unitid
    local name = unit.name
    --if (addSoon and WarGodU)
    local score = 10
    if name ~= bossString then
        score = 20
    end
    if UnitIsUnit(unitid, "target") then
        score = score + 5
    end
    return score, bossString
    --return WGBM.default.Priority(spell, unitid, args)
end

WGBM[bossString].Purge = function(spell, unit, args)
    local unitid = unit.unitid
    if UnitClass("player") == "Mage" then
        return

    end
    if UnitClassification(unitid) == "elite" then
        return true
    end
    return true
end

WGBM[bossString].Cleanse = function(spell, unit, args)
    local unitid = unit.unitid
    local embalmingRemains, stacks = unit:BuffRemaining("Embalming Fluid", "HARMFUL")
    if stacks > 0 and stacks < 2 then
        return
    end
    return true
end

WGBM[bossString].Interrupt = function(spell, unit, args)
    local unitid = unit.unitid
    if UnitCastingInfo(unitid) == "Deathly Chill" then
        return
    end
    return true
    --printTo(3,'default interrupt')
end

WGBM[bossString].ExtraHealthMissing = function(spell, unit, args)
    local total = 0
    local unitid = unit.unitid
    for i = 1, 5 do
        local debuffName = UnitDebuff(unitid,i)
        if not debuffName then
            break
        end
        if debuffName == "Poison Barrage" then
            --local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2
        elseif debuffName == "Severing Blade" then
            --local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2
        elseif debuffName == "Lingering Poison" then
            --local amount = select(16, UnitDebuff(unitid, i))
            --print(amount)
            total = total + unit.health_max * 0.2
        end
    end
    return total
    --local debuffName, _, _, _, _, _, _, _,_,_,_,_,_, _, _,absorbAmount = UnitDebuff("player",i)=="Immunosuppression"
    --/run for i=1,5 do if UnitDebuff("player",i)=="Immunosuppression" then print(select(16, UnitDebuff("player",i))) end end
end